apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp-deployment
spec:
  selector:
    matchLabels:
      app: demoapp-project
  replicas: 2
  revisionHistoryLimit: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: demoapp-project
    spec:
      containers:
      - name: demoapp-project
        image: k2r2t2/demo-image
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
